### ISSUE TITLE
Plugin will not search in new extension directory when version of `redhat.java` is updated

### ISSUE THREAD

**Issue by Vigilans** [testforstephen/vscode-pde#11]
When language support of java is updated from 0.48 to 0.49, the plugin still search for the config in the old dir:
```
[Error - 10:52:55 PM] Sep 23, 2019 10:52:55 PM The current target platform contains errors, open Window > Preferences > Plug-in Development > Target Platform for details.
Problems occurred while resolving the target contents
org.eclipse.core.runtime.CoreException: Problems occurred while resolving the target contents
	at org.eclipse.pde.internal.core.PluginModelManager.getExternalBundles(PluginModelManager.java:681)
	at org.eclipse.pde.internal.core.PluginModelManager.initializeTable(PluginModelManager.java:591)
	at org.eclipse.pde.internal.core.PluginModelManager.targetReloaded(PluginModelManager.java:522)
	at org.eclipse.pde.internal.core.RequiredPluginsInitializer.lambda$0(RequiredPluginsInitializer.java:33)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Configuration directory does not exist: /Users/vigilans/.vscode/extensions/redhat.java-0.48.0/server/config_mac/
```

The same problem occured when updated from 0.47 to 0.48.

**Comment by Vigilans** [comment]
Sorry, seems that it's not the issue with pde plugin, but in
```
[Trace - 11:13:10 PM] Received notification 'language/progressReport'.
Params: {
    "id": "6595ea06-4913-47a0-bcd2-4341d9e35f63",
    "task": "Initializing plug-in models",
    "status": "Initializing plug-in models - 0%",
    "totalWork": 1000,
    "workDone": 0,
    "complete": false
}
```
