### ISSUE TITLE
JUnit Plugin Test: java.lang.IllegalArgumentException: Error: parameter '-port' not specified

### ISSUE THREAD

**Issue by Eskibear** [testforstephen/vscode-pde#12]
```
PS C:\Users\yanzh\Work\eclipse.jdt.ls\org.eclipse.jdt.ls.tests> & 'C:\Users\yanzh\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.23.0\scripts\launcher.bat' 'C:\Users\yanzh\AppData\Local\Programs\AdoptOpenJDK\\bin\java' '-ea' '-Declipse.pde.launch=true' '-Declipse.p2.data.area=@config.dir\p2' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\yanzh\AppData\Roaming\Code - Insiders\User\workspaceStorage\c99dd0402562385d82dc2e7a23cabb5f\redhat.java\jdt_ws\.metadata\.plugins\org.eclipse.pde.core\.bundle_pool\plugins\org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar' 'org.eclipse.equinox.launcher.Main' '-os' 'win32' '-ws' 'win32' '-arch' 'x86_64' '-nl' 'en_US' '-consoleLog' '-version' '3' '-testLoaderClass' 'org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader' '-loaderpluginname' 'org.eclipse.jdt.junit4.runtime' '-classNames' 'org.eclipse.jdt.ls.core.internal.correction.StaticImportQuickAssistTest' '-application' 'org.eclipse.pde.junit.runtime.nonuithreadtestapplication' '-testApplication' 'org.eclipse.pde.junit.runtime.coretestapplication' '-data' 'C:\\Users\\yanzh\\AppData\\Roaming\\Code - Insiders\\User\\workspaceStorage\\c99dd0402562385d82dc2e7a23cabb5f\\redhat.java\\jdt_ws/../junit-workspace' '-configuration' 'file:C:/Users/yanzh/AppData/Roaming/Code - Insiders/User/workspaceStorage/c99dd0402562385d82dc2e7a23cabb5f/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.pde.core/pde-junit/' '-dev' 'file:C:/Users/yanzh/AppData/Roaming/Code - Insiders/User/workspaceStorage/c99dd0402562385d82dc2e7a23cabb5f/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.pde.core/pde-junit/dev.properties' '-os' 'win32' '-ws' 'win32' '-arch' 'x86_64' '-nl' 'en_US' '-consoleLog' '-testpluginname' 'org.eclipse.jdt.ls.tests'
!SESSION 2019-11-06 13:53:02.537 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_222
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -version 3 -testLoaderClass org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader -loaderpluginname org.eclipse.jdt.junit4.runtime -classNames org.eclipse.jdt.ls.core.internal.correction.StaticImportQuickAssistTest -application org.eclipse.pde.junit.runtime.nonuithreadtestapplication -testApplication org.eclipse.pde.junit.runtime.coretestapplication -testpluginname org.eclipse.jdt.ls.tests
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -consoleLog -version 3 -testLoaderClass org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader -loaderpluginname org.eclipse.jdt.junit4.runtime -classNames org.eclipse.jdt.ls.core.internal.correction.StaticImportQuickAssistTest -application org.eclipse.pde.junit.runtime.nonuithreadtestapplication -testApplication org.eclipse.pde.junit.runtime.coretestapplication -data C:\\Users\\yanzh\\AppData\\Roaming\\Code - Insiders\\User\\workspaceStorage\\c99dd0402562385d82dc2e7a23cabb5f\\redhat.java\\jdt_ws/../junit-workspace -dev file:C:/Users/yanzh/AppData/Roaming/Code - Insiders/User/workspaceStorage/c99dd0402562385d82dc2e7a23cabb5f/redhat.java/jdt_ws/.metadata/.plugins/org.eclipse.pde.core/pde-junit/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -testpluginname org.eclipse.jdt.ls.tests

!ENTRY org.eclipse.core.resources 2 10035 2019-11-06 13:53:04.030
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.osgi 4 0 2019-11-06 13:53:04.625
!MESSAGE Application error
!STACK 1
java.lang.IllegalArgumentException: Error: parameter '-port' not specified
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:356)
        at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.init(RemotePluginTestRunner.java:264)
        at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:161)
        at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:27)
        at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:57)
        at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:49)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
An error has occurred. See the log file
C:\Users\yanzh\AppData\Roaming\Code - Insiders\User\workspaceStorage\c99dd0402562385d82dc2e7a23cabb5f\redhat.java\junit-workspace\.metadata\.log.
```

**Comment by Eskibear** [comment]
@jdneo , possibly a regression of test runner. It works well with vscode-java-test@0.20.0
